const Theme = {
    ltr: "ltr",
    rtl: "rtl",
    placeholder: "editor-placeholder",
    paragraph: "editor-paragraph",
    quote: "editor-quote",
    heading: {
        h1: "editor-heading-h1",
        h2: "editor-heading-h2",
        h3: "editor-heading-h3",
        h4: "editor-heading-h4",
        h5: "editor-heading-h5"
    },
    list: {
        ol: "editor-list-ol",
        ul: "editor-list-ul"
    },
    listitem: "editor-listitem",
    image: "editor-image",
    text: {
        bold: "editor-text-bold",
        link: "editor-text-link",
        italic: "editor-text-italic",
        overflowed: "editor-text-overflowed",
        hashtag: "editor-text-hashtag",
        underline: "editor-text-underline",
        strikethrough: "editor-text-strikethrough",
        underlineStrikethrough: "editor-text-underlineStrikethrough",
        code: "editor-text-code"
    },
    code: "editor-code",
    horizontal: 'editor-horizontal',
    codeHighlight: {
        atrule: 'PlaygroundEditorTheme__tokenAttr',
        attr: 'PlaygroundEditorTheme__tokenAttr',
        boolean: 'PlaygroundEditorTheme__tokenProperty',
        builtin: 'PlaygroundEditorTheme__tokenSelector',
        cdata: 'PlaygroundEditorTheme__tokenComment',
        char: 'PlaygroundEditorTheme__tokenSelector',
        class: 'PlaygroundEditorTheme__tokenFunction',
        'class-name': 'PlaygroundEditorTheme__tokenFunction',
        comment: 'PlaygroundEditorTheme__tokenComment',
        constant: 'PlaygroundEditorTheme__tokenProperty',
        deleted: 'PlaygroundEditorTheme__tokenProperty',
        doctype: 'PlaygroundEditorTheme__tokenComment',
        entity: 'PlaygroundEditorTheme__tokenOperator',
        function: 'PlaygroundEditorTheme__tokenFunction',
        important: 'PlaygroundEditorTheme__tokenVariable',
        inserted: 'PlaygroundEditorTheme__tokenSelector',
        keyword: 'PlaygroundEditorTheme__tokenAttr',
        namespace: 'PlaygroundEditorTheme__tokenVariable',
        number: 'PlaygroundEditorTheme__tokenProperty',
        operator: 'PlaygroundEditorTheme__tokenOperator',
        prolog: 'PlaygroundEditorTheme__tokenComment',
        property: 'PlaygroundEditorTheme__tokenProperty',
        punctuation: 'PlaygroundEditorTheme__tokenPunctuation',
        regex: 'PlaygroundEditorTheme__tokenVariable',
        selector: 'PlaygroundEditorTheme__tokenSelector',
        string: 'PlaygroundEditorTheme__tokenSelector',
        symbol: 'PlaygroundEditorTheme__tokenProperty',
        tag: 'PlaygroundEditorTheme__tokenProperty',
        url: 'PlaygroundEditorTheme__tokenOperator',
        variable: 'PlaygroundEditorTheme__tokenVariable',
    },
    table: 'editor-table',
    tableCell: 'editor-table-cell',
    tableCellHeader: 'editor-table-cell-header',
};

export default Theme;
